name: Deploy Lambda Function

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'
    
    - name: Test Lambda function
      run: |
        cd receive_jira_webhook
        go test
        cd ../convert_inquiry_by_chatgpt
        go test

    - name: Build Lambda function
      run: |
        cd receive_jira_webhook
        GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o main main.go
        zip function.zip main
        cd ../convert_inquiry_by_chatgpt
        GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o main main.go
        zip function.zip main

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy to Lambda functions
      run: |
        aws lambda update-function-code --function-name receiveJiraWebhook --zip-file fileb://receive_jira_webhook/function.zip
        aws lambda update-function-code --function-name convertInquiryByChatGPT --zip-file fileb://convert_inquiry_by_chatgpt/function.zip
