name: Deploy Lambda Function

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.20'

    - name: Build Lambda function
      run: |
        GOOS=linux GOARCH=amd64 go build -o bootstrap main.go  # main.goはLambda関数のエントリポイント
        zip function.zip bootstrap
    
    - name: Deploy to AWS Lambda
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'ap-northeast-1'

    - name: Deploy to multiple Lambda functions
      run: |
        for function_name in getJiraWebhook
        do
          aws lambda update-function-code --function-name $function_name --zip-file fileb://bootstrap.zip
        done
