name: Deploy Lambda Function

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Lambda function using Docker
      run: |
        docker run --rm -v "$PWD":/usr/src/polite_inquiry_converter -w /usr/src/polite_inquiry_converter golang:1.20 sh -c '
          apt-get update &&
          apt-get install -y zip &&
          cd receive_jira_webhook &&
          go build -buildvcs=false -o main &&
          zip /usr/src/polite_inquiry_converter/receive_jira_webhook/function.zip main
        '

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy to Lambda functions
      run: aws lambda update-function-code --function-name receiveJiraWebhook --zip-file fileb://receive_jira_webhook/function.zip
