name: Deploy Lambda Function

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'

    - name: Build Lambda function
      run: |
        cd receive_jira_webhook
        GOOS=linux GOARCH=amd64 go build -o main main.go
        zip function.zip main
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy to multiple Lambda functions
      run: |
        for function_name in receiveJiraWebhook
        do
          aws lambda update-function-code --function-name $function_name --zip-file fileb://receive_jira_webhook/function.zip
        done
